{
  enable = true;
  enableFishIntegration = true;
  brews = [
    "bat"
    "carapace"
    "cmake"
    "cmatrix"
    "podman"
    "podman-compose"
    "eza"
    "fastfetch"
    "fd"
    "ffmpeg"
    "fish"
    "fzf"
    "gcc"
    "gnupg"
    "kubernetes-helm"
    "helmfile"
    "kubectl"
    "lima"
    "minikube"
    "nasm"
    "neovim"
    "ninja"
    "nodejs"
    "openssh"
    "openssl"
    "pass"
    "pinentry-mac"
    "qemu"
    "ripgrep"
    "rustup"
    "sevenzip"
    "sqlite"
    "starship"
    "stow"
    "tmux"
    "unzip"
    "wakeonlan"
    "wget"
    "xh"
    "xz"
    "yazi"
    "yt-dlp"
    "zoxide"
    "caddy"
  ];
  casks = [
    "copilot-cli"
    "ghostty"
    "openclaw"
    "podman-desktop"
    "rar"
    "slack"
    "wireshark-app"
    "iina"
    "localsend"
    "tailscale-app"
    "yoink"
    "nikitabobko/tap/aerospace"
    "codex-app"
    "superwhisper"
    "wallspace"
    "moonlight"
    "vesktop"
  ];
  # Auto deletes any brews/casks that are not specified in the configuration
  onActivation.cleanup = "zap";

  # Updates (obviously)
  onActivation.autoUpdate = true;
  onActivation.upgrade = true;
}
